### ISSUE TITLE
Release schedule

### ISSUE THREAD

**Issue by gnilrets** [v0dro/daru#100]
So we've had some massive improvements to performance over the last two months.  Could we get a release?  Also, it looks like development has really picked up lately and I want to make use of those enhancements in the projects I've got that are using Daru.  What do you think about making biweekly or monthly releases?

**Comment by v0dro** [comment]
Monthly looks good. How about we release a new version at the end of each month (given that things don't break and there are no features are incomplete)?

I havn't released a new version yet because GSOC is coming up and students are busy reviewing and contributing to daru. But I like your idea of scheduled releases.

A new version will be released by the 4th week of April for sure.

**Comment by gnilrets** [comment]
Sounds good to me.  Thanks!
