### ISSUE TITLE
Accessing multiple vectors in Daru::DataFrame with `#[]` or `#vector` is extremely slow

### ISSUE THREAD

**Issue by agisga** [v0dro/daru#13]
In a `Daru::DataFrame` with 1000 rows and 3 columns (named `a`, `b` and `c`) I have benchmarked
`v1 = df.vector[:c]` against
`v2 = df.vector[:a..:b]` and against
`v3 = df.vector[:a, :c]`.
Accessing one vector takes less than a millisecond, but accessing two vectors at a time takes ages. The elapsed times don't change if I use `df[...]` instead of `df.vector[...]`.

Here are the results:

```
*** Extract one vector :c ***
Elapsed time: 0.011007 milliseconds
*** Extract a range :a..:b of vectors ***
Elapsed time: 2400.41752 milliseconds
*** Extract multiple vectors, :a,:c ***
Elapsed time: 2414.85577 milliseconds
```

Here, the same experiment for a data with 10000 rows and 3 columns. It took in total more than 8 minutes on my Intel-core-i5-12GB-RAM-laptop:

```
*** Extract one vector :c ***
Elapsed time: 0.027409000000000003 milliseconds
*** Extract a range :a..:b of vectors ***
Elapsed time: 256343.461203 milliseconds
*** Extract multiple vectors, :a,:c ***
Elapsed time: 251004.597329 milliseconds
```

This is possibly related to issue [#12](https://github.com/v0dro/daru/issues/12).

Also, please let me know if you know of a workaround, because this issue makes the user friendly methods of [mixed_models](https://github.com/agisga/mixed_models) practically not applicable for data with >10000 rows.

(I am currently using the stable release daru gem, because gsl-nmatrix fails to get installed on my machine for some reason. So, I'm sorry if this is already fixed in the most recent development version.)

**Comment by v0dro** [comment]
Thanks a ton for pointing this out.

I know of a fix. Hold on.

Btw don't use `#vector` anymore, its being removed in favor of `#[]` for the next release.

**Comment by v0dro** [comment]
Alright, I've fixed it in [this branch](https://github.com/v0dro/daru/tree/tseries). Please use that code.

You wont require gsl-nmatrix anymore because I've changed the development dependency to `rb-gsl ~> 1.16`, which does not depend on narray and is compatible with nmatrix.

Also see the benchmark script that I've added [here](https://github.com/v0dro/daru/blob/tseries/benchmarks/vector_access.rb). Thanks to you access time has been significantly improved now :)

Also, if you have any more benchmarks in mind feel free to send a PR on the tseries branch or send me a gist.

**Comment by agisga** [comment]
I tested your recent `tseries` branch code. Access times are A LOT faster now. Thank for fixing it so quickly! :)

**Comment by agisga** [comment]
Related question:

What is there fastest way to access a subset of the rows of a `Daru::DataFrame`?

Say, I have data with 50000 rows, but 20000 of them contain "bad" values (like missing data or incorrect measurements). I want to get rid of the "bad" rows.
I tried to do `df.row[*good_rows]`, and I also tried  to delete the bad rows one by one with `#delete_row`. However, both options seem veeery slooow (I'm still experimenting, so no benchmarks yet).

**Comment by v0dro** [comment]
Accessing rows with `df.row[*good_rows]` would be fastest right now. Since you asked I've added a [new benchmark script too](https://github.com/v0dro/daru/blob/master/benchmarks/row_access.rb). Do remember to pull the latest daru from my master branch. I've made further optimizations.

Access with ranges is slow because of something in Daru::Index. I'll speed that up tonight. For now use `#to_a` on ranges and pass them as an Array into the `row[]` method.

**Comment by v0dro** [comment]
Row access with ranges is also now MUCH faster and is at par with row access by specifying row numbers. See [this commit](https://github.com/v0dro/daru/commit/7a1cffe52fda97d087a8128abffbb0079390e67b) for details.

Dont use delete_row too many times since it needs to re create the internal data structures every time it is called. If you'll ask me its purely a convenience function and I'd personally discourage using it unless absolutely necessary.

Here are the [new benchmarks for row access](https://github.com/v0dro/daru/blob/master/benchmarks/row_access.rb). Do pull my latest master.

**Comment by agisga** [comment]
Perfect :)

**Comment by v0dro** [comment]
PS: Don't forget to let me know if you find more issues!
