### ISSUE TITLE
Proposal: get rid of missing_values concept completely

### ISSUE THREAD

**Issue by zverok** [v0dro/daru#137]
**Reasons**:

1. `Vector#set_missing_positions` is needed on any vector update and is slow (entire `Daru.lazy_update` trick exists to fight it);
2. The concept is pretty confusing (and, to be honest, I'm not sure even inside Daru always used correctly -- there are ton of simple `nil`-checks here and there, and eventual "right" missing-data checks);
3. Ruby has native `nil`, which has the exact "there is no value" meaning.

As far as I can understand, the concept of "user decides what is 'missing values'" is borrowed from environments where "no values" can be represented by strings like 'None' or 'Nothing', or 'Unknown' etc. I'm pretty sure that the only place in Daru such data should be supported is input and output. So, when fetching data from CSV with `"None"`s, we can provide some option (like `missing: "None"`) -- and they would be stored internally as `nil`s. And, when saving to CSV, we provide same option -- and again, `nil`s are converted to `"None"`s or whatever user wants.

This change will help to greatly simplify API, codebase, docs, and Daru user's mental model.

**Comment by v0dro** [comment]
@gnilrets @mrkn any comments here? I've come across some use cases where missing data was something apart from just `nil`.

**Comment by v0dro** [comment]
Btw I just remembered that some functionality in statsample depends on this particular feature. If we decide to support only `nil` as missing (and even maybe `Float::NAN`) we'll need changes in both daru and statsample.

**Comment by v0dro** [comment]
This is how statsample looked before dataset was replaced with Daru::DataFrame - https://github.com/SciRuby/statsample/blob/63280a31849bb6320eecda04445cc43d34932ae8/lib/statsample/dataset.rb

**Comment by zverok** [comment]
I've just `grep`ed through statsample code, and it is not much of `missing_<anything>` features usage. I assume it should not be hard to update, and we all will benefit from this... Though, I'm sometimes feeling like being too pushing in SciRuby matters and need to slow myself a little :)

**Comment by mrkn** [comment]
I agree with that 'replacing missing values with nil or Float::NAN.

**Comment by mrkn** [comment]
I think the concept of `set_missing_positions` can be divided to scanning whole dataframe and updating  index of missing values.
The current implementation does only scanning.
But updating index is enough for the almost point at which `set_missing_positions` is called.

**Comment by v0dro** [comment]
OK as per what @zverok is saying, we will drop support for missing values apart from nil and Float::NAN in future versions.

**Comment by lokeshh** [comment]
> OK as per what @zverok is saying, we will drop support for missing values apart from nil and Float::NAN in future versions.

Why are we supporting `Float::NAN` in addition to nil?

**Comment by v0dro** [comment]
It so happens that numerical libraries like nmatrix frequently use Float::NAN for representing missing data in a floating point matrix.

**Comment by lokeshh** [comment]
So how would the new API look like. Currently we have:
- `only_valid` to print only the valid values. This will now print values except `nil` and `Float::NAN`
- `has_missing_data?` to tell if there are missing values.
- `missing_positions` give positions of missing values. Should we cache the missing positions as currently done by `@missing_positions`?
- `exists?` returns true if a value is there in the vector and is treated as missing values. This shouldn't be needed anymore. I think we should remove it because one can simply do `#include?` and there is no missing values except `nil` and `Float::NAN`.
- `n_valid` returns the number of non missing values. This should too work as it as.
- `missing_values` returns the list of missing values
- `only_missing` returns list of missing values. I think this would be no more useful as this would now only return list of `nil`s and `Float::NAN`s.

Further, should we have the instance variables `@missing_positions` and `@missing_values`? I propose we remove it so we don't have to update them every time make an update. Although I haven't thought about the down sides.

**Comment by agisga** [comment]
@lokeshh I agree with you. Apart from the methods you mention, I have also found the data frame methods `#missing_values_rows`, `#clone_only_valid` and `#dup_only_valid`, which I think are worth keeping if possible.

**Comment by lokeshh** [comment]
@agisga I'll keep that in mind. Thank you :+1:

**Comment by v0dro** [comment]
> only_valid to print only the valid values. This will now print values except nil and Float::NAN

Not print. It returns a new data structure without missing values.

> has_missing_data? to tell if there are missing values. This should also work like before.

Yes.
> missing_positions give positions of missing values. Should we cache the missing positions as currently done by @missing_positions?

Yes caching would make it much faster. We should explore optimizing storage of missing positions in a later issue.
> exists? returns true if a value is there in the vector and is treated as missing values. This shouldn't be needed anymore. I think we should remove it because one can simply do #include? and there is no missing values except nil and Float::NAN.

OK works.
> n_valid returns the number of non missing values. This should too work as it as.
Yep.
> missing_values returns the list of missing values
Yes. In a vector.
> only_missing returns list of missing values. I think this would be no more useful as this would now only return list of nils and Float::NANs.
OK. Indexes of the missing data can be found using missing_positions anyway.

OK

> Further, should we have the instance variables @missing_positions and @missing_values? I propose we remove it so we don't have to update them every time make an update on the vector. Although I haven't thought about the down sides.

This is debatable. Maybe we can optimize it somehow (my earlier comment) or remove it and port the looping that will happen to C or something because everytime the user wants to know the missing positions we will need to loop over the whole vector.

So keep these for now. Don't remove.

**Comment by zverok** [comment]
To be honest, the proposal was targeting serious simplifications of APIs and concepts. It may be to extreme, but what seems a "happy path" for me, is the following:

1. Consider only "Ruby native" missing concept (`nil`)
  * `Float::NaN` could be transparently converted into `nil` on assignment...
  * ...or left intact, without any special processing (see below about it);
2. Get rid of _all_ special `*_missing_*` and `*_valid_*` methods in favor of generic methods with same functionality (replacement methods has "drafty" names):
  * `has_missing_values?` → `include?(*values)` (e.g. `include?(nil, Float::NaN)`, but also `include?(0)` or basically everything);
  * `only_valid` → `reject(*values)`
  * `missing_positions` → `indexes(*values)`
  * `n_valid` → `count(*values)`
  * And `fillna` (or anything similar, as per #198) could just be `replace(from_value, to_value)` or even `replace([from_values], to_value)`

And the note of "missingness" could then be used only for:
* method like Ruby's `Array#compact` (and maybe some other, _thorougly selected_, shortcuts for generic methods);
* reading/writing options (like in original issue description, when reading/writing to CSV and specifying `missing: 'NONE'` option)

**Comment by v0dro** [comment]
Hmmm I like @zverok's idea. @lokeshh how would you go about this? The caching of missing data should still happen so you will need to treat calls to `include?`, `reject` etc. differently if the arguments are `nil` or `Float::NAN`.

About treating only `nil` as missing: the problem is that `nil` is an object and `Float::NAN` is a floating point number. Should we decide to switch to nmatrix for storage, the whole vector will need to be `:object` just because it contains `nil`, which will be a big overhead and will nullify the advantages of nmatrix.

And @lokeshh you will also need to make appropriate changes in statsample and statsample-glm so that the new API is supported. Also use a deprecation mechanism for gracefully deprecating these methods.

**Comment by agisga** [comment]
My main concern is that I want to be able work with missing values directly on data frames rather than iterating through the vectors.

For example if I want to check that a data frame has missing values, it would be inconvenient to call #include on every vector (that's why I like the method #has_missing_data for data frames).
Or a lot of times I want to extract a new data frame that contains only the rows which have no missing data from the original data frame (I think currently there is the method #dup_only_valid for that).
Etc.

What I'm saying is that if you follow @zverok's idea, then I think it is necessary to also have versions of those methods for data frames.

**Comment by lokeshh** [comment]
`#include?` and `#reject` in dataframe perform different functions. Lets stick to `#has_missing_data` and `#dup_only_valid` for dataframes while we use the method names like `#include?` and `#reject` as suggested by @zverok. What do you think?

**Comment by lokeshh** [comment]
Now that I think about it more, lets change `#has_missing_data?` in `Daru::DataFrame` to `#include_values?(*values)` and `#dup_only_valid` to `#reject_values(*values)`. It makes more sense because this way we can map the methods related to missing data used in `Daru::Vector` to `Daru::DataFrame` by adding "values" suffix. Also it makes sense to have something like `#include_values?` because here the arguments are values not vectors.

**Comment by lokeshh** [comment]
> Hmmm I like @zverok's idea. @lokeshh how would you go about this? The caching of missing data should still happen so you will need to treat calls to include?, reject etc. differently if the arguments are nil or Float::NAN.

Ok. I think this shouldn't be difficult. First I will create `include?`, `reject`, etc and later cache them for `nil` and `Float::NAN`.

> Also use a deprecation mechanism for gracefully deprecating these methods.
This can be tricky since the deprecated methods would require `@missing_positions` and if we do not remove `@missing_positions` then there will be no speed up.

**Comment by v0dro** [comment]
How will the missing positions be kept updated without `set_missing_positions`? If we don't cache the missing positions, we'll need to run through them every time the method is called. Something tells me that we CAN get away with leaving this to the user.

 @gnilrets @mrkn what do you think? Would it be justified to leave caching of missing positions to users? That way we can also get rid of `Daru.lazy_update`, which I think is not a very great feature, and daru's internals will also be simplified.

**Comment by v0dro** [comment]
> EDIT: One correction. I was wrong about #include? and #reject being reserved in Daru::DataFrame. But anyway I think they shouldn't be used to accept values, rather they should work considering dataframe a collection of vectors.

You can use `include_values?` in dataframe for knowing if a particular value exists. `include?` can accept Vectors.

**Comment by mrkn** [comment]
I think missing points cache is reasonable to process missing values as fast as possible for the too large data frame.

In machine learning, we often replaces missing values with representative values of vector in missing data imputation process.

**Comment by v0dro** [comment]
How about having methods like `fillna` in `daru/shortcuts`? It will just be a wrapper over `replace`.

**Comment by lokeshh** [comment]
I was thinking, lets just rename methods like `include?`, `reject` which are to be implemented in `Daru::Vector` to `include_values?`, `reject_values`, etc. because of the following reason:
- It will match the terminology of corresponding methods in `Daru::DataFrame`
- `reject` is defined by Enumerable to only accept a block and making it doing two things i.e. accept a block as well as accept arguments, will make the code a little complex.

What do you think?

**Comment by v0dro** [comment]
Hmmm @zverok what do you think about this?

**Comment by zverok** [comment]
@v0dro @lokeshh  Seems pretty reasonable to me
