### ISSUE TITLE
[Cleanup] Reduce variable caching

### ISSUE THREAD

**Issue by zverok** [v0dro/daru#173]
Some examples:
* `@vectors` in DataFrame;
* `@size` in DataFrame and Vector.

Their calculation is 100% trivial, and I have an (easily verifiable) theory that performance drawback, if any, would be insignificant. And code would be seriously simpler, reducing probability of bugs like those: https://github.com/v0dro/daru/issues/172.

**Comment by v0dro** [comment]
`@vectors` and `@size` are created only when the DF/Vector is created. In case of `@vectors` how do you propose to store order?

**Comment by zverok** [comment]
> `@vectors` and `@size` are created only when the DF/Vector is created.

And they need to be synchronized on order change or adding/removing rows. Which can lead to all kind of unintuitive behavior, like this:
```ruby
df = Daru::DataFrame.new(a: [1,2,3], b: [4,5,6])
df.add_vector :c, Daru::Vector.new([1,2,3])
df
# => #<Daru::DataFrame(3x3)>
#       a   b   c
#   0   1   4   1
#   1   2   5   2
#   2   3   6   3 
df[:a].name
# => :a 
df[:b].name
# => :b 
df[:c].name
# => nil -- ????
```

>  In case of `@vectors` how do you propose to store order?

Just naturally, as an order of vectors in `@data` array. For all I know, changing order of _small_ array (even containing _large_ objects) should be pretty cheap operation. Like, 
```ruby
def vectors= idx
  @data = @data.sort_by { |v| idx.index(v.name) }
  self
end
```

PS: On a side note, this part of an API seems really unfortunate to me :( For all my intuition, `df.vectors` should be a vectors list proxy (like `df.vectors.add` and so on), and `df.order` can/should return list of vector names...

**Comment by v0dro** [comment]
Hmmm ok so according to you the basic problem is that we're storing vector names in two different places, the actual names of vectors in the `@data` array and in the `@vectors`? But what if it's indexed on something other than simple names? Say `DateTimeIndex`? It requires querying by year/month/day etc. What if indexing is eventually made extensible enough to let users create their own index classes and use them for indexing data?

I think the problem here is that we're storing a DF as a set of Vectors. IMO if we can devise a functionality that can somehow represent data in a DF as a simple 2D matrix and somehow broadcast operations performed on a DF to the relevant columns of the internal 2D matrix then that would be great.

**Comment by zverok** [comment]
> But what if it's indexed on something other than simple names?

Hmm, that makes sense, forgot about it (even funnier considering I've recently done rendering of DFs with multi-index column names). That complicates matters, of course.

> I think the problem here is that we're storing a DF as a set of Vectors.

Maybe you are right. But maybe if internals would be 2D matrix, the operations of add column/remove column became expensive, which is pretty bad.

I'll close this and will look into matters when I'll have more time (maybe after GSoC, so discussions of redesigns would not interfere with large and important work Lokesh performs).

**Comment by v0dro** [comment]
Sure. I think we should explore the way in which pandas stores data.
