### ISSUE TITLE
Get vector using instance method when name is string

### ISSUE THREAD

**Issue by lokeshh** [v0dro/daru#187]
```ruby
> df = Daru::DataFrame.new(
>   :a => [1, 2, 3],
>   'b' => [4, 5, 6]
> )
> df.a
#=> #works
> df.b
#=> #doesn't work
```
I propose to let let vectors with string names similarly processed. WDYT?

**Comment by gnilrets** [comment]
I can think of at least one edge case which would be weird:
````ruby
df = Daru::DataFrame.new(
:a => [1,2,3],
'a' => [4,5,6]
)
df.a #=> ????
````

Not sure about everyone else, but I strongly prefer the array accessor method getting vectors - `df[:a]`.

**Comment by gnilrets** [comment]
Something that's always bothered me about this is that when you use `df[:a]` you get a vector, but when you use `df[:a, :b]` you get a dataframe.  This could be a problem if I'm creating a new dataframe from a variable list of vectors and it's possible for that list to just have one element.  What would everyone think about using `df[:a]` to return a dataframe and `df.a` to return a vector?

**Comment by zverok** [comment]
This thing is something I've wanted to discuss a long time ago :) Considering not-so-easy Ruby's String/Symbol dychotomy, it could be (maybe) reasonable for all real-life cases to make them indistinguishable from internal point of view (like infamous `HashWithIndifferentAccess`).

Most of the times, when somebody has `:a` and `'a'` vector in the same dataset, it does NOT what he/she wanted, but rather the result of some logical error.

**Comment by zverok** [comment]
> Something that's always bothered me about this is that when you use `df[:a]` you get a vector, but when you use `df[:a, :b]` you get a dataframe. 

This thing is normal for Ruby:
```ruby
arr = ('a'..'e').to_a
# => ["a", "b", "c", "d", "e"] 
arr[3]
# => "d" 
arr[3,4]
# => ["d", "e"] 

```

**Comment by lokeshh** [comment]
> Something that's always bothered me about this is that when you use df[:a] you get a vector, but when you use df[:a, :b] you get a dataframe. This could be a problem if I'm creating a new dataframe from a variable list of vectors and it's possible for that list to just have one element.

I've encountered the same problem. You can use `df[:a..:a]` if you want a dataframe and not a vector. Generalizing it you can do something like following:
```ruby
# Assume x contains list of vectors names
x.size == 1 ? df[x.first..x.first] : df[*x] # This will return a dataframe even when x has one element.
```
I think we can also create another method for this type of usage.

**Comment by v0dro** [comment]
It does not make sense to return a DataFrame with a single vector because:
- As @zverok pointed out, when you select a single element, the result is an element of a type that makes up that collection (in this case `Daru::Vector`).
- DataFrame still involves duplication of indexes and is heavier than Vector. Thus it would be unnecessary overhead.

We can overcome this problem by having a `to_df` method on `Daru::Vector` which will create a DataFrame out of the Vector. The `to_df` method on `Daru::DataFrame` will simply return `self`. @gnilrets thoughts?

**Comment by v0dro** [comment]
@lokeshh about your original issue:

The `df.vector_name` syntax is more of a convenience syntax. We should support all sorts of vector names irrespective of whether are symbols or strings.

@gnilrets the edge case that you pointed out (where there's a symbol and string name in the same dataframe) will most likely be a fault on part of the user and even if it is intentional the user can easily use the `#[]` method for accessing vectors.

Therefore I think we should support vector names that use strings.

**Comment by gnilrets** [comment]
`to_df` on vectors would be a great workaround.

As far as the string/symbol, I agree that it would be more natural to internally convert strings to symbols when using `df.a`.
