### ISSUE TITLE
'row, vector' Nomenclature is confusing

### ISSUE THREAD

**Issue by graft** [v0dro/daru#19]
In several places you refer to 'rows' and 'vectors', and by default you seem to think of a data frame as organized in columns. I find this confusing, especially since both a row and a column in a DF are of class Daru::Vector. It would be nice if this nomenclature was agnostic and treated rows and columns equally. I.e., #filter currently defaults to columns, and #filter(:row) is how you filter across rows. I would vastly prefer either #filter_rows and #filter_columns or #filter(:col) and #filter(:row), etc. I don't see any particularly good reason to assume that rows or columns are primary, and if it comes to that I tend to assume row => record, so that by default I would filter across rows.

**Comment by v0dro** [comment]
These functions exist. The `#filter(axis_name)` function exists only as a convienience function. There is `#filter_vectors` and `#filter_rows` which work exactly the way you're expecting them to (which `#filter` calls internally).

Iterating over vectors is faster than iterating over columns. DataFrame is intended to be a data-complete, collection of heterogeneous column arrays (Daru::Vector objects). Higher precedence is given to vectors over rows because that's the way its represented internally. Maybe later if the implementation is changed to represent a DataFrame as one huge matrix this might change.

**Comment by graft** [comment]
It is just plain ambiguous to say filter_vectors when you clearly mean filter_columns. I don't think the internal representation should be presented to the user at all; a data frame is a matrix-like object and should be agnostic about rows vs. columns, so I think that's how the interface should look to the user. What's powerful about a data frame is that you can search/select across rows and columns simultaneously, and the interface should facilitate this.

**Comment by v0dro** [comment]
A column is just called a vector. That's something we inherited from statsample. Why is it ambiguous? Once you internalize the fact that a column is a Vector in daru, everything should fall into place.

IMO if you use the library more it should not feel ambiguous at all.
