### ISSUE TITLE
Can't rename columns?

### ISSUE THREAD

**Issue by graft** [v0dro/daru#20]
It seems to me that there is no way to rename columns, currently. You can access information about rownames and column names via #vectors and #index (which I think is unclear, see #19), both of which return a Daru::Index. However, there is no straightforward way to modify these values without remapping to an entirely new data frame, which seems a fairly large hole. Internally this information is stored both in @relation_hash, which is exposed but frozen, and in @keys, which is not exposed but seems redundant with @relation_hash.keys.

It seems like renaming rows or columns could be done by supporting an interface to rename keys in the Index, perhaps by keeping the @relation_hash unfrozen and exposing a []= method to remap a key.

**Comment by graft** [comment]
I'll try to whip up a PR that might address this issue, might take me a few days. Pretty psyched to have found this project! This is important work.

**Comment by agisga** [comment]
You can rename columns with a syntax like

```Ruby
my_data_frame.vectors = Daru::Index.new([:new_name1, :new_name2, :new_name3])
```

and analogously for rows.

Also see [these examples](https://github.com/v0dro/daru/blob/tseries/spec/dataframe_spec.rb#L1266)

**Comment by graft** [comment]
The R idiom from which this descends is much more flexible, since the row/column names are just treated as vectors, meaning I can edit them in-place (i.e., change just one column name):
```
    colnames(df)[2] = "roger"
```
It should be possible to just rename one column, I would think. Also, why assign a Daru::Index rather than using a Daru::Vector to store/manipulate these names? Those already allow all of this mass-assignment stuff.

**Comment by v0dro** [comment]
When you use a Daru::Index to reassign the names of the rows or vectors, you can use the full range of Index objects available in Daru (`Index`, `MultiIndex` and `DateTimeIndex`). It also serves as a sanity check of sorts so that invalid indexes aren't assigned (for example those containing duplicate objects, which `Daru::Index` does not yet support).

To rename the vector of DataFrame, I have a syntax in mind. We can call a `#rename` function on the Daru::Vector. The only problem is that the Vector will somehow need to reflect this change back to the DataFrame, because a DataFrame basically consists of Daru::Vector objects internally. All this should be done without affecting Vector's stand alone functionality.

And btw, using `#vectors=` or `#rows=` will only change the names of the indexes. If you want to conduct a reindexing with preservation of the named data, you can use [#reindex](http://www.rubydoc.info/gems/daru/0.1.1/Daru%2FDataFrame%3Areindex).

**Comment by graft** [comment]
It seems like there are two different functions being performed by an Index - to store unique names for a row/column and to facilitate selections on them. I'm not sure this requires its own sort of object rather than making use of the already-available Vector type, which should allow both of these operations (assignment and selection).

The way R does selections is pretty simple - selections can take one of two forms, a logical vector or a set of row/column identifiers, and the [] interface of a dataframe responds to both of these. Daru is already pretty far afield from this level of simplicity, which is going to get hairier and hairier. If this is meant to be a simple, accessible base class, we shouldn't have to reach inside it to make secondary objects to manipulate it in these fundamental ways.

**Comment by v0dro** [comment]
There are 3 index objects, with many more to come. Each has its own unique behavior that adds to daru's indexing functionality. I suggest you take the time of going through the blogs and notebooks and try to understand the reason behind separate objects for indexing before suggesting to do away with them.
