### ISSUE TITLE
Plotting timeseries

### ISSUE THREAD

**Issue by pedrocunha** [v0dro/daru#26]
Hi @v0dro,

Cheers, this is amazing.

Is there a strong dependency on "gnuplotrb" to plot timeseries ? 

Consider the following example:
```
historical_data = [
  ["2015-08-30", 309],
  ["2015-09-06", 331],
  ["2015-09-13", 279],
  ["2015-09-20", 294],
  ["2015-09-25", 253]
].map { |element|
  Hash.new.tap do |hash|
    hash["date"]  = element[0]
    hash["total"]  = element[1]
  end
}

df = Daru::DataFrame.new(data)
df.plot(type: :line, y: :date, x: :total) do |plot, diagrams|
 ...
end
```

This doesn't seem to plot out of the box the timeseries on y axis. I've tried converting date to `Date` or `DateTime`. Am i missing something or this only works through the datetime ranges and via `gnuplotrb`?

Thanks

**Comment by v0dro** [comment]
Yes the problem is that nyaplot (which is what is used in the default #plot function) does not yet support DateTime plotting, so plotting can be done be gnuplotrb.

Gnuplotrb has been modified to support Date DateTime ranges. You might want to first convert your normal `Index` to a `DateTimeIndex` to support better plotting of time series.

See the README for more details on DateTimeIndex.

**Comment by pedrocunha** [comment]
Cheers @v0dro.
