### ISSUE TITLE
mikon vs daru?

### ISSUE THREAD

**Issue by minad** [v0dro/daru#5]
It seems both of you are working on dataframe libraries?

https://github.com/v0dro/daru
https://github.com/domitry/mikon

What about merging these two?

**Comment by v0dro** [comment]
Mikon started off after daru, but @domitry made some amazing progress in very little time.

I have borrowed some functionality from mikon in daru. For example, the idea of using the library as the primary data store for statsample was first proposed there (and which daru is now implementing here - https://github.com/SciRuby/statsample/pull/35).

Daru has grown a lot more in features since then and can do everything that mikon can (except the Mikon::Row DSL, which I think is very interesting). It also additionally sports group_by, pivot_table and hierarchical indexing now, and will soon have time series handling.

So mikon is mostly merged into daru, so to speak.

**Comment by minad** [comment]
It would probably be the best if one of the projects is continued and you join your efforts. This will lead to a better thing in the end, more review and more discussions about the needed features since the features should fulfil both your requirements.

**Comment by v0dro** [comment]
Agreed.

**Comment by agarie** [comment]
It would be great indeed! Sameer is doing a good job at making Statsample work with Daru's DataFrame and Vector (this should be done and shipped in a new statsample version in a few weeks). I'm pretty sure the same could be done in Nyaplot, thus leading to a single DataFrame-like structure being used in several different and useful gems.
