### ISSUE TITLE
Default order of vectors

### ISSUE THREAD

**Issue by gnilrets** [v0dro/daru#59]
What are your thoughts on removing the alphabetic sort of vectors when initializing new data and just go with the order they come in?

https://github.com/v0dro/daru/blob/master/lib/daru/dataframe.rb#L2336

I read a lot of data from CSV files and would prefer the columns to show up in the same order that they appear in the file.  Data typically comes in with the more important fields on the left (id's and names, for example).  We could probably make some changes that would only affect CSVs, but I'm wondering if it makes sense to make it more general.

**Comment by v0dro** [comment]
That line is called only when the DataFrame is initialized from a `Hash` without specifying the order of the vectors:
``` ruby
Daru::DataFrame.new({ b: [1,2,3], a: [2,3,4]})
#=> 
#<Daru::DataFrame:99220630 @name = 1be64f57-ab82-47fc-af86-1ecc3ec9a799 @size = 3>
#                    a          b 
#         0          2          1 
#         1          3          2 
#         2          4          3 
```

If you explicitly specify the `order:` option then it won't happen. Since you're talking about CSV files, I think we can add functionality that will first get the headers of the CSV file, and then pass those in the `:order` attribute of the dataframe so that the ordering of the vectors will be the way it is in the CSV. That would be more logical than the way it is now.
