### ISSUE TITLE
Nyaplot required?

### ISSUE THREAD

**Issue by mohawkjohn** [v0dro/daru#6]
If I try to `require "daru"`, it gives me the following error message (twice):

```
cannot load such file -- nyaplot
cannot load such file -- nyaplot
```

Why is nyaplot required? Shouldn't it be possible to do analyses without it installed?

**Comment by v0dro** [comment]
It is possible.

This was happening due a mistake that I made in the way it was being required. Fixed it in https://github.com/v0dro/daru/commit/bbb5adb0da963983fbacb751b8dd8d1eab049896

**Comment by mohawkjohn** [comment]
Same issue for gsl-nmatrix. Is GSL really required for normal usage?

**Comment by v0dro** [comment]
No it isn't.

Its supposed to work without gsl-nmatrix in it's current state. Could you tell me what exactly is going wrong so that I can fix it?

It seems to be working fine on my machine with/without GSL or nyaplot. The nyaplot require warning doesn't appear anymore either.

**Comment by mohawkjohn** [comment]
If I do bundle install, it complains about a lack of gsl-nmatrix. Maybe
that's just because I was doing it in-tree.

**Comment by v0dro** [comment]
Yes. You'll need to first run `gem install nmatrix-0.1.0.gem` and then  `gem install gsl-nmatrix-1.17.gem` in the daru root directory.

This needs to be done because testing requires the latest versions of these gems, which are contained in the .gem files that ship in the daru source repo. I'll be replacing them with a script soon, but this is a work around until then.
